name: mixmil_envf3
channels:
 - pytorch
 - nvidia
 - conda-forge
 - defaults
dependencies:
 - python=3.11
 - pytorch=2.5.0
 - torchvision
 - torchaudio
 - pytorch-cuda=12.4
 - pip
 - jupyterlab
 - ipykernel
 - ipywidgets
 - scanpy
 - anndata
 - statannotations
 - pip:
     - --find-links https://data.pyg.org/whl/torch-2.5.0+cu124.html
     - torch-scatter==2.1.2
     - filelock==3.20.2

